name: modernbert
channels:
  - nvidia/label/cuda-12.4.1
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - binutils_impl_linux-64=2.43
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - cuda=12.4.1
  - cuda-cccl=12.4.127
  - cuda-command-line-tools=12.4.1
  - cuda-compiler=12.4.1
  - cuda-cudart=12.4.127
  - cuda-cudart-dev=12.4.127
  - cuda-cudart-static=12.4.127
  - cuda-cuobjdump=12.4.127
  - cuda-cupti=12.4.127
  - cuda-cupti-static=12.4.127
  - cuda-cuxxfilt=12.4.127
  - cuda-demo-suite=12.4.127
  - cuda-documentation=12.4.127
  - cuda-driver-dev=12.4.127
  - cuda-gdb=12.4.127
  - cuda-libraries=12.4.1
  - cuda-libraries-dev=12.4.1
  - cuda-libraries-static=12.4.1
  - cuda-nsight=12.4.127
  - cuda-nsight-compute=12.4.1
  - cuda-nvcc=12.4.131
  - cuda-nvdisasm=12.4.127
  - cuda-nvml-dev=12.4.127
  - cuda-nvprof=12.4.127
  - cuda-nvprune=12.4.127
  - cuda-nvrtc=12.4.127
  - cuda-nvrtc-dev=12.4.127
  - cuda-nvrtc-static=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-nvvp=12.4.127
  - cuda-opencl=12.4.127
  - cuda-opencl-dev=12.4.127
  - cuda-profiler-api=12.4.127
  - cuda-sanitizer-api=12.4.127
  - cuda-toolkit=12.4.1
  - cuda-tools=12.4.1
  - cuda-visual-tools=12.4.1
  - gcc=13.3.0
  - gcc_impl_linux-64=13.3.0
  - gds-tools=1.9.1.3
  - gxx=13.3.0
  - gxx_impl_linux-64=13.3.0
  - kernel-headers_linux-64=3.10.0
  - ld_impl_linux-64=2.43
  - libcublas=12.4.5.8
  - libcublas-dev=12.4.5.8
  - libcublas-static=12.4.5.8
  - libcufft=11.2.1.3
  - libcufft-dev=11.2.1.3
  - libcufft-static=11.2.1.3
  - libcufile=1.9.1.3
  - libcufile-dev=1.9.1.3
  - libcufile-static=1.9.1.3
  - libcurand=10.3.5.147
  - libcurand-dev=10.3.5.147
  - libcurand-static=10.3.5.147
  - libcusolver=11.6.1.9
  - libcusolver-dev=11.6.1.9
  - libcusolver-static=11.6.1.9
  - libcusparse=12.3.1.170
  - libcusparse-dev=12.3.1.170
  - libcusparse-static=12.3.1.170
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-devel_linux-64=13.3.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - liblzma=5.6.4
  - libnpp=12.2.5.30
  - libnpp-dev=12.2.5.30
  - libnpp-static=12.2.5.30
  - libnsl=2.0.1
  - libnvfatbin=12.4.127
  - libnvfatbin-dev=12.4.127
  - libnvjitlink=12.4.127
  - libnvjitlink-dev=12.4.127
  - libnvjpeg=12.3.1.117
  - libnvjpeg-dev=12.3.1.117
  - libnvjpeg-static=12.3.1.117
  - libsanitizer=13.3.0
  - libsqlite=3.49.1
  - libstdcxx=14.2.0
  - libstdcxx-devel_linux-64=13.3.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - nsight-compute=2024.1.1.4
  - openssl=3.4.1
  - pip=25.0.1
  - python=3.12.9
  - readline=8.2
  - sysroot_linux-64=2.17
  - tk=8.6.13
  - uv=0.6.5
  - wheel=0.45.1
